// Generates docs/RBAC.md from the permission catalogue so docs never drift from code.
import { writeFileSync } from "node:fs";
import { PERMISSIONS, SYSTEM_ROLES, type Permission } from "../src/lib/rbac/permissions";

const roles = Object.keys(SYSTEM_ROLES);
const byModule = new Map<string, Permission[]>();
for (const p of Object.keys(PERMISSIONS) as Permission[]) {
  const m = p.split(":")[0];
  byModule.set(m, [...(byModule.get(m) ?? []), p]);
}
const sym = { ALL: "All", TEAM: "Team", SELF: "Self" } as const;
let md = `# HRsoft RBAC — Roles × Permissions\n\n_Generated by \`npx tsx scripts/gen-rbac-doc.ts\` from \`src/lib/rbac/permissions.ts\`. Do not edit by hand._\n\n`;
md += `## Model\n\n- A **permission** is \`module:action\`.\n- Each role grants a permission at a **scope**: **Self** (own records), **Team** (self + direct and indirect reports, resolved with a recursive CTE on \`Employee.managerId\`), **All**.\n- A user's effective scope for a permission is the **widest** scope across all of their roles.\n- Services enforce RBAC with \`authorize(actor, permission, { employeeId })\` and \`scopeFilter(actor, permission)\`; the UI only hides what the server already forbids.\n- Custom roles can be created in **Settings → Roles & Access**; \`SUPER_ADMIN\` is immutable.\n\n## Roles\n\n`;
for (const r of roles) md += `- **${r}** — ${SYSTEM_ROLES[r].name}: ${SYSTEM_ROLES[r].description}\n`;
md += `\n## Matrix\n\n`;
for (const [mod, perms] of byModule) {
  md += `### ${mod}\n\n| Permission | Description | ${roles.join(" | ")} |\n|---|---|${roles.map(() => "---").join("|")}|\n`;
  for (const p of perms) {
    const cells = roles.map((r) => {
      const g = SYSTEM_ROLES[r].grants.find(([perm]) => perm === p);
      return g ? sym[g[1]] : "—";
    });
    md += `| \`${p}\` | ${PERMISSIONS[p]} | ${cells.join(" | ")} |\n`;
  }
  md += "\n";
}
writeFileSync("docs/RBAC.md", md);
console.log("wrote docs/RBAC.md");
